# 1. Basis-Image mit JDK 17
FROM openjdk:17-jdk

# 2. Arbeitsverzeichnis im Container setzen
WORKDIR /app

# 3. Abhängigkeiten und Code kopieren
COPY target/fullstack-trainer-backend-0.0.1-SNAPSHOT.jar app.jar

# 4. Port freigeben
EXPOSE 8080

# 5. Startbefehl für Spring Boot
ENTRYPOINT ["java", "-jar", "app.jar"]
