# Stage 1: Build the React app
FROM node:21 AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# Baue die Anwendung mit Development-Modus
RUN npm run build:dev

# Stage 2: Produktions-Image
FROM nginx:latest

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]