# Stage 1: Build the React app
FROM node:21 AS builder

WORKDIR /app

# Kopiere package.json und installiere Abhängigkeiten
COPY package.json ./
RUN npm install

# Kopiere den Rest des Projekts und führe den Build aus
COPY . .

# Baue die Anwendung
RUN npm run build

# Stage 2: Erstelle das Produktions-Image
FROM nginx:latest

# Kopiere die gebauten Dateien aus der Build-Phase in das HTML-Verzeichnis
COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

# Exponiere den Port 80 für Nginx
EXPOSE 80

# Starte Nginx im Vordergrund
CMD ["nginx", "-g", "daemon off;"]
